FROM eclipse-temurin:21
ENV MONGODB_HOST=${MONGODB_HOST} MONGODB_USER=${MONGODB_USER} MONGODB_PASSWORD=${MONGODB_PASSWORD} MONGODB_LOCAL_PORT=${MONGODB_LOCAL_PORT}
WORKDIR /app
COPY build/libs/joblisting-0.0.1.jar joblisting-0.0.1.jar
EXPOSE 8080
CMD ["java -DMONGODB_HOST=$MONGODB_HOST -DMONGODB_USER=$MONGODB_USER -DMONGODB_PASSWORD=$MONGODB_PASSWORD -DMONGODB_LOCAL_PORT=$MONGODB_LOCAL_PORT","-jar","joblisting-0.0.1.jar"]
