ktor:
    application:
        modules:
            - com.fgiaquintaruiz.ApplicationKt.module
    deployment:
        port: 8080

db:
    mongo:
        host: cluster0.29zfo.mongodb.net
        port: 27017