ktor:
    application:
        modules:
            - com.fgiaquintaruiz.ApplicationKt.module
    deployment:
        port: 8080

db:
    mongo:
        host: $MONGODB_HOST
        port: $MONGODB_LOCAL_PORT
        user: $MONGODB_USER
        password: $MONGODB_PASSWORD